######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 16:11:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    solarsystem.cpp \
    stars.cpp

HEADERS += \
    stars.hpp \
    solarsystem.hpp
